### ISSUE TITLE
[Feature Request] Logging of custom training metrics

### ISSUE THREAD

**Issue by JanS97** [facebookresearch/mbrl-lib#108]
# 🚀 Feature Request

When training a model with `ModelTrainer`, it would be nice to be able to log some custom metrics (ideally in tensorboard), defined by the model (e.g., the values of the individual loss terms if the loss of the model is a sum of multiple terms). Right now one can only access the overall loss of the model.

## Motivation

**Is your feature request related to a problem? Please describe.**

At the moment I am working on a model that optimizes a sum of reconstruction loss, reward prediction loss, and a kl divergence term. For debugging purposes it would be nice to monitor how the individual losses evolve over time.
This logging can not be done by the model class on its own since it needs some information from the RL algorithm (e.g. the current iteration of the algorithm / number of samples drawn from the environment) for the logged values to be meaningful.

## Pitch

**Describe the solution you'd like**

The simplest solution certainly is to just allow passing kwargs to `ModelTrainer.train()`, which are passed through to `Model.update()`. This would allow to pass some custom logging function / object that then logs values passed by the model implementation.
This is of course not the most elegant solution, but the kwargs could also be used for other purposes (e.g. passing some additional information to `Model.update()` if a model implementation requires this).

**Describe alternatives you've considered**

An alternative to this would be to let `Model.update()` return a dictionary of metrics in addition to the loss. This dictionary could then be returned by `ModelTrainer.train()` or it could be processed by the callback passed to the function.
This would of course cause breaking changes since the method signature of `Model` would need to be changed.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Yes

**Comment by luisenp** [comment]
Thanks for the request, @JanS97! I agree this would be a useful feature. While working on PlaNet I was thinking of a solution which is basically the second alternative you describe (but I haven't implemented yet). Namely, `Model.update()` now returns a dictionary of anything the user deems relevant (maybe as a second output), and then the callback takes care of the additional logging. I'd prefer to keep the model trainer code agnostic to the particular logger used by the user. 

It's true that this is a breaking change, but hopefully the user impact is not so large, since `update` is mostly used by the model trainer. We could also add some temporary logic for the trainer to handle ouputs in the old format and emit a deprecation warning, while this becomes the official solution (which I have in mind for v0.2.0, when the PlaNet code is ready to merge). 

Any thoughts on this?

**Comment by JanS97** [comment]
I believe this is the best solution to the problem. However, I think we need to modify the functions `Model.loss()` and `Model.eval_score()` to return such a dictionary as well. In my case, the individual loss terms are calculated by `Model.loss()`. The default implementation of `Model.update()` should then just pass through the dictionary from `Model.loss()`. Having `Model.eval_score()` return a dictionary would allow to e.g. record the same metrics on evaluation data.

I agree that the `ModelTrainer` should be agnostic to the logger that is used. Using the callback to do the logging is a good solution here.

As you said, the impact of the breaking change should not be too large since the functions mentioned above should all be used only by `ModelTrainer` and `Model` itself. However, changing the signature of the callback function might also cause problems, so we should keep some temporary logic that deals with callback functions that do not have the extra argument for the dictionary.

**Comment by luisenp** [comment]
Good point about the callback! OK, since this feature would be immediately useful for several people, I'll work on adding it next week in a separate branch. I can tag you in the pull request if you are interested in reviewing :)

**Comment by JanS97** [comment]
Sure, let me know if I can help you with anything

**Comment by robertocalandra** [comment]
Yes, I think this would be a very useful feature!

**Comment by luisenp** [comment]
@JanS97 Following up on this, in case you didn't receive notifications about #109 (and if you'd like to take a look).

**Comment by JanS97** [comment]
Thanks for implementing this so quickly. I have been a bit busy, so I have not looked at it yet. I'll have a look later today.
