### ISSUE TITLE
[Bug] Normalization of model inputs causes PETS to crash on Pybullet Half Cheetah

### ISSUE THREAD

**Issue by MarkSelden** [facebookresearch/mbrl-lib#110]
## Steps to reproduce

  1. Run PETS algorithm from example notebook with Pybullet Halfcheetah instead of Cartpole env using the code I put at the bottom. 
  2. Alternatively, set ```normalize: true``` in the algorithm parameters for any environment with an observation which doesn't change before normalization is attempted. 

## Observed Results

When running the code below I get the following Traceback and error:

> Traceback (most recent call last):
  File "/Users/markselden/learning/mbrl-lib/tests/algorithms/test_halfcheetah_normalizer.py", line 161, in <module>
    next_obs, reward, done, _ = common_util.step_env_and_add_to_buffer(env, obs, agent, {}, replay_buffer)
  File "/Users/markselden/learning/mbrl-lib/mbrl/util/common.py", line 398, in step_env_and_add_to_buffer
    action = agent.act(obs, **agent_kwargs)
  File "/Users/markselden/learning/mbrl-lib/mbrl/planning/trajectory_opt.py", line 340, in act
    plan = self.optimizer.optimize(trajectory_eval_fn)
  File "/Users/markselden/learning/mbrl-lib/mbrl/planning/trajectory_opt.py", line 224, in optimize
    best_solution = self.optimizer.optimize(
  File "/Users/markselden/learning/mbrl-lib/mbrl/planning/trajectory_opt.py", line 134, in optimize
    values = obj_fun(population)
  File "/Users/markselden/learning/mbrl-lib/mbrl/planning/trajectory_opt.py", line 337, in trajectory_eval_fn
    return self.trajectory_eval_fn(obs, action_sequences)
  File "/Users/markselden/learning/mbrl-lib/mbrl/planning/trajectory_opt.py", line 398, in trajectory_eval_fn
    return model_env.evaluate_action_sequences(
  File "/Users/markselden/learning/mbrl-lib/mbrl/models/model_env.py", line 173, in evaluate_action_sequences
    _, rewards, dones, _ = self.step(action_batch, sample=True)
  File "/Users/markselden/learning/mbrl-lib/mbrl/models/model_env.py", line 116, in step
    next_observs, pred_rewards = self.dynamics_model.sample(
  File "/Users/markselden/learning/mbrl-lib/mbrl/models/one_dim_tr_model.py", line 274, in sample
    preds = self.model.sample(model_in, rng=rng, deterministic=deterministic)[0]
  File "/Users/markselden/learning/mbrl-lib/mbrl/models/model.py", line 319, in sample
    return (torch.normal(means, stds, generator=rng),)
RuntimeError: normal expects all elements of std >= 0.0

After debugging I have located the source of the error. In line 138 of `util/math` linked [here](https://github.com/facebookresearch/mbrl-lib/blob/ffc4e7e7c20f71c16bf75ef444244314e650c44f/mbrl/util/math.py#L138). The normalize function  divides the model input tensor by the std tensor. For input features which the model has not yet seen change the std is 0. Dividing by 0 places NaNs in the normalized model input tensor. The model then cannot handle the NaNs. 

## Expected Results

The PETS algorithm to run smoothly.

## Relevant Code
This is the code I am running which produces the error, it is mostly pulled from [pets_example.ipynb](https://github.com/facebookresearch/mbrl-lib/blob/master/notebooks/pets_example.ipynb)
  ```
  import matplotlib as mpl
import numpy as np
import torch
import omegaconf


import mbrl.env.termination_fns as termination_fns
import mbrl.models as models
import mbrl.planning as planning
import mbrl.util.common as common_util
import mbrl.util as util
import pybullet_envs
import gym
print('test')

mpl.rcParams.update({"font.size": 16})

device = 'cuda:0' if torch.cuda.is_available() else 'cpu'

seed = 16
env = gym.make('HalfCheetahBulletEnv-v0')
env.seed(seed)
rng = np.random.default_rng(seed=0)
#I believe the generator is used for random sampling
generator = torch.Generator(device=device)
generator.manual_seed(seed)
obs_shape = env.observation_space.shape
act_shape = env.action_space.shape

# This functions allows the model to evaluate the true rewards given an observation
# This function allows the model to know if an observation should make the episode end
term_fn = termination_fns.no_termination

trial_length = 200
num_trials = 10
ensemble_size = 5

# Everything with "???" indicates an option with a missing value.
# Our utility functions will fill in these details using the
# environment information
cfg_dict = {
    # dynamics model configuration
    "dynamics_model": {
        "model": {
            "_target_": "mbrl.models.GaussianMLP",
            "device": device,
            "num_layers": 3,
            "ensemble_size": ensemble_size,
            "hid_size": 200,
            "use_silu": True,
            "in_size": "???",
            "out_size": "???",
            "deterministic": False,
            "propagation_method": "fixed_model"
        }
    },
    # options for training the dynamics model
    "algorithm": {
        "learned_rewards": True,
        "target_is_delta": True,
        "normalize": True,
    },
    # these are experiment specific options
    "overrides": {
        "trial_length": trial_length,
        "num_steps": num_trials * trial_length,
        "model_batch_size": 32,
        "validation_ratio": 0.05
    }
}
cfg = omegaconf.OmegaConf.create(cfg_dict)

# Create a dynamics model for this environment
#dynamics_model = models.GaussianMLP(obs_shape + act_shape, obs_shape + 1)
dynamics_model = util.common.create_one_dim_tr_model(cfg, obs_shape, act_shape)

replay_buffer = util.common.create_replay_buffer(
    cfg, obs_shape, act_shape, rng=rng
)

util.common.rollout_agent_trajectories(
    env,
    50,
    planning.RandomAgent(env),
    {},
    replay_buffer=replay_buffer,
)

# Create a gym-like environment to encapsulate the model
model_env = models.ModelEnv(
        env, dynamics_model, term_fn, generator=generator
    )


agent_cfg = omegaconf.OmegaConf.create({
    # this class evaluates many trajectories and picks the best one
    "_target_": "mbrl.planning.TrajectoryOptimizerAgent",
    "planning_horizon": 30,
    "replan_freq": 5,
    "verbose": False,
    "action_lb": "???",
    "action_ub": "???",
    # this is the optimizer to generate and choose a trajectory
    "optimizer_cfg": {
        "_target_": "mbrl.planning.CEMOptimizer",
        "num_iterations": 5,
        "elite_ratio": 0.1,
        "population_size": 500,
        "alpha": 0.1,
        "device": device,
        "lower_bound": "???",
        "upper_bound": "???",
        "return_mean_elites": True
    }
})

agent = planning.create_trajectory_optim_agent_for_model(
    model_env,
    agent_cfg,
    num_particles=15
)
train_losses = []
val_scores = []

def train_callback(_model, _total_calls, _epoch, tr_loss, val_score, _best_val):
    train_losses.append(tr_loss)
    val_scores.append(val_score.mean().item())   # this returns val score per ensemble model


# Create a trainer for the model
model_trainer = models.ModelTrainer(dynamics_model, optim_lr=1e-3, weight_decay=5e-5)


# Main PETS loop
all_rewards = [0]
for trial in range(num_trials):
    obs = env.reset()
    agent.reset()

    done = False
    total_reward = 0.0
    steps_trial = 0
    while not done:
        # --------------- Model Training -----------------
        if steps_trial == 0:
            dynamics_model.update_normalizer(replay_buffer.get_all())  # update normalizer stats

            dataset_train, dataset_val = replay_buffer.get_iterators(
                batch_size=cfg.overrides.model_batch_size,
                val_ratio=cfg.overrides.validation_ratio,
                train_ensemble=True,
                ensemble_size=ensemble_size,
                shuffle_each_epoch=True,
                bootstrap_permutes=False,  # build bootstrap dataset using sampling with replacement
            )

            model_trainer.train(
                dataset_train, dataset_val=dataset_val, num_epochs=50, patience=50, callback=train_callback)

        # --- Doing env step using the agent and adding to model dataset ---
        next_obs, reward, done, _ = common_util.step_env_and_add_to_buffer(env, obs, agent, {}, replay_buffer)

        obs = next_obs
        total_reward += reward
        steps_trial += 1

        if steps_trial == trial_length:
            break

    all_rewards.append(total_reward)


  ```

**Comment by luisenp** [comment]
HI @MarkSelden, thanks a lot for your interest and for reporting. I will push a fix for soon (probably in the next couple of days), as part of a change where normalization uses double precision by default, instead of floats (see #99 for some discussion). Sorry about the inconvenience, and thanks for the effort you put into this report.

**Comment by luisenp** [comment]
@MarkSelden #111 has the fixes and changes I mentioned. I'm waiting for the results of some tests before merging, but the fix should be in the new release very soon.

**Comment by MarkSelden** [comment]
Thanks for closing this out quickly! Much appreciated.
