### ISSUE TITLE
Could you please provide the data corresponding to the figures of of experiments in the paper——PETS? Because we would like to like cite PETS as one of the state of the art work in our paper, but time is limited. Thank you![Feature Request]

### ISSUE THREAD

**Issue by curiosityoftiane** [facebookresearch/mbrl-lib#114]
# 🚀 Feature Request

## Motivation

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by luisenp** [comment]
Hi @curiosityoftiane. Are you referring to the original PETS paper? Note that this repository was not the one used to write that paper.
