### ISSUE TITLE
[Feature Request] cartpole_continuous.py is not the standard continuous cartpole

### ISSUE THREAD

**Issue by robertocalandra** [facebookresearch/mbrl-lib#117]
# 🚀 Feature Request

The cartpole system implemented in cartpole_continuous is not the standard cartpole used in most of the control literature. We should implement also the standard cartpole.

## Motivation

**Is your feature request related to a problem? Please describe.**
The current cartpole_continuous uses discrete actions, and a reward function which is 1 within the given angle cone.
The traditional control cartpole instead uses continuous actions, and as a reward function the Euclidean distance between the tip of the pendulum and a given point upright. Moreover, the cartpole starts from a down-pointing position. Overall this configuration is a harder problem, and more commonly used in the control community, compared to the one currently implemented.

## Pitch

**Describe the solution you'd like**
I suggest renaming the current cartpole_continuous to cartpole_discrete, and instead create a new cartpole_continuous following the implementation by Chua et al. (https://github.com/kchua/handful-of-trials/blob/master/dmbrl/env/cartpole.py)

**Comment by hxri** [comment]
> # 🚀 Feature Request
> The cartpole system implemented in cartpole_continuous is not the standard cartpole used in most of the control literature. We should implement also the standard cartpole.
> 
> ## Motivation
> **Is your feature request related to a problem? Please describe.**
> The current cartpole_continuous uses discrete actions, and a reward function which is 1 within the given angle cone.
> The traditional control cartpole instead uses continuous actions, and as a reward function the Euclidean distance between the tip of the pendulum and a given point upright. Moreover, the cartpole starts from a down-pointing position. Overall this configuration is a harder problem, and more commonly used in the control community, compared to the one currently implemented.
> 
> ## Pitch
> **Describe the solution you'd like**
> I suggest renaming the current cartpole_continuous to cartpole_discrete, and instead create a new cartpole_continuous following the implementation by Chua et al. (https://github.com/kchua/handful-of-trials/blob/master/dmbrl/env/cartpole.py)

Hi

Can I work on this?

**Comment by luisenp** [comment]
Hi @hxri, thanks for the offer! Before working on this, we should clarify that the version in the `envs` folder is indeed continuous. See [this](https://github.com/facebookresearch/mbrl-lib/blob/master/mbrl/env/cartpole_continuous.py#L108) line, and contrast it with the original gym version, [here](https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py#L108). Unfortunately, it looks like I never updated the documentation to reflect what this version of cartpole does. 

I'm happy with adding the version that @robertocalandra suggests, named as `cartpole_pets_version.py`, and your contribution (@hrxi) on this would definitely be welcome :)

**Comment by hxri** [comment]
> I'm happy with adding the version that @robertocalandra suggests, named as `cartpole_pets_version.py`, and your contribution (@hrxi) on this would definitely be welcome :)

Sure! I am happy to work on it.

Can you please clarify what actually I need to implement? 

Is it implementing (https://github.com/kchua/handful-of-trials/blob/master/dmbrl/env/cartpole.py) as cartpole_pets_version.py?
or is it something else?

**Comment by luisenp** [comment]
Yes, then make sure that it runs and learns using PETS, and add a default config to this folder --> https://github.com/facebookresearch/mbrl-lib/tree/master/mbrl/examples/conf/overrides
