### ISSUE TITLE
Reward setup of the HalfCheetah environment

### ISSUE THREAD

**Issue by jihwan-jeong** [facebookresearch/mbrl-lib#118]
Hello! Firstly, thanks for the awesome codebase :)

I have a very simple question regarding the way the halfcheetah environment is set up. Clearly, you seem to have just ported the implementation of the environment in the original PETS repo, but I wanted to ask here just in case you have an idea of what's going on. 

So, when you compute the reward, you use the following equations
```
reward_ctrl = -0.1 * np.square(action).sum(axis=action.ndim - 1)
reward_run = next_ob[..., 0] - 0.0 * np.square(next_ob[..., 2])
reward = reward_run + reward_ctrl
```

In the second line of the above snippet, the second term that is being subtracted will always have the value of zero. I wonder what's then the purpose of having the term in the first place.

Thanks!

**Comment by luisenp** [comment]
HI @jihwan-jeong, thanks a lot for the comment! 

To be honest, I don't know why it was set up this way and I didn't look too much into this. The environments in `mbrl/env/` are there mostly for debugging and comparing our codebase with the original algorithm implementations. I would however encourage people to use standard `gym` versions whenever possible (e.g., MBPO works well with standard HalfCheetah). I'm considering adding a README to this folder to clarify this intent, as maybe having them be part of the library sends a bit of a confusing signal.

**Comment by jihwan-jeong** [comment]
Hi @luisenp,

Thanks for your reply and clarification!

> I'm considering adding a README to this folder to clarify this intent, as maybe having them be part of the library sends a bit of a confusing signal.

Indeed, I think that's a good way to prevent confusion such as the one I had.
