### ISSUE TITLE
[Feature Request] Add PyBullet implementations of envs

### ISSUE THREAD

**Issue by dtch1997** [facebookresearch/mbrl-lib#130]
# 🚀 Feature Request

Add PyBullet-backed implementations of standard envs such as those described here: https://github.com/benelot/pybullet-gym

## Motivation

Mujoco is a paid software whereas PyBullet is open-source and of equal quality. This would allow those without Mujoco licenses to have access to the codebase. 

## Pitch

**Describe the solution you'd like**
PyBullet implementations of standard environments are added to the repository. 

**Are you willing to open a pull request?** 
Yes

**Comment by dtch1997** [comment]
I know this has already been raised in https://github.com/facebookresearch/mbrl-lib/pull/87 but that hasn't been updated in 2 months, it seems like development work has stopped and I'd be willing to pick it up / start over.

**Comment by luisenp** [comment]
Hi @dtch1997, this is something we we definitely want to support, and would be happy to have you pick it up if you are interested.
