### ISSUE TITLE
[Bug] RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by melfm** [facebookresearch/mbrl-lib#173]
## Steps to reproduce

Just trying to run the example environment with MBPO.

  1. python -m mbrl.examples.main algorithm=mbpo overrides=mbpo_halfcheetah

## Observed Results

I noticed this error happens when the flag `self.use_only_elite = True` and something in the weight multiplication goes wrong.

``` 
~/mbrl-lib/mbrl/models/util.py", line 55, in forward
    xw = x.matmul(self.weight[self.elite_models, ...])
RuntimeError: CUDA error: device-side assert triggered
```

I'm not sure if there is a problem with installation or versioning from my end, but the notebook examples seem to run fine.

**Comment by luisenp** [comment]
Hi @melfm. Sorry for the delay. I have an internal deadline today and this slipped off my mind. Do you still have this issue? What `torch` version are you using?

**Comment by melfm** [comment]
Hi @luisenp - I'm using `torch '1.8.1+cu111'` and `Python 3.8.8`. The pets_example.ipynb runs fine though but not when I run the main examples.

**Comment by melfm** [comment]
Gotcha! The requirements indicate `PyTorch (>= 1.7)` so I didn't realize 1.8 would be problematic. I will try `torch==1.12.1`.

**Comment by luisenp** [comment]
Maybe it's some compatibility issue between the CUDA version and the torch version. The error doesn't happen for me in torch 1.8.1 with CUDA 10.2.

**Comment by melfm** [comment]
Ok I see! I will explore different versioning for this issue then. Thanks a lot!
