### ISSUE TITLE
Add script to analyze results from multiple runs and display statistics

### ISSUE THREAD

**Issue by luisenp** [facebookresearch/mbrl-lib#33]
Given a run using Hydra multirun folder structure, and our logger output, display results with confidence intervals and summary statistics.

**Comment by a3ahmad** [comment]
I've started on a basic training results viewer in my fork, what would be the best way to collaborate and have it ideally hit your goals here?

**Comment by natolambert** [comment]
I made this before I was aware of how the diagnostics folder was structured, maybe we should move it there? https://github.com/facebookresearch/mbrl-lib/blob/plotting/notebooks/plot_over_trials.ipynb

**Comment by luisenp** [comment]
@a3ahmad @natolambert Thanks a lot! A pull request would be the best way to get started, then we can discuss there a bit if any adjustments are necessary :)

**Comment by a3ahmad** [comment]
Done, this is a first pass effort I initially built for my own use. But since you had a similar ask I thought I would offer it as a starting point. Happy to make any changes to bolster it, if you feel it's worthwhile. If not, no problem -- I'll keep using it locally :)

**Comment by luisenp** [comment]
Close by #77
