### ISSUE TITLE
pets_example.ipynb problem

### ISSUE THREAD

**Issue by app1ep1e** [facebookresearch/mbrl-lib#83]
i run the pets_example.ipynb and what i get the following error:

i am not sure if it's my package's compatible problem.
so i am not sure following error is bug or not.
python:3.7.10
nmupy: 1.20.1
matplotlib: 3.4.2 
torch:1.7.1 py3.7_cuda10.1.243_cudnn7.6.3_0

1. 
TypeError: normal() received an invalid combination of arguments when run the main loop
i found the model_env arg 'rng'  is np.random.default_rng(seed=0), not torch.normal
 ```
# Create a gym-like environment to encapsulate the model
#model_env = models.ModelEnv(env, dynamics_model, term_fn, reward_fn, rng)
```
2. 
TypeError: can't convert cuda:0 device type tensor to numpy. when run the plot part
when the gpu is on, val_score tensor is (0.0023, device='cuda:0') and cause error in plot part
 ```
def train_callback(_model, _total_calls, _epoch, tr_loss, val_score, _best_val):
    train_losses.append(tr_loss)
    #val_scores.append(val_score.mean())   # this returns val score per ensemble model
```

**Comment by luisenp** [comment]
Thanks for reporting! I don't think it's a compatibility issue, it's related to some small changes I pushed recently. I'll push a fix tonight/tomorrow, thanks.

**Comment by app1ep1e** [comment]
@luisenp thanks for your reply! 
1 is solved, but 2 still has porblem for me.
I tried to switch `matplotlib` to 3.4.1 not solve the problem, and due to torch 1.8.1 not support CUDA 10.1 and i will graduation soon,  the experiment on my thesis is based on tensorflow, so i don't want to change anything can cause my code error before graduation. install tensorflow is a nightmare.

**Comment by luisenp** [comment]
No problem, I was mostly curious. I just pushed a fix, can you try it and let me know if it works for you? Thanks!

**Comment by app1ep1e** [comment]
@luisenp sorry, i didn't say clear, your fix is works for me, just problem 2 i change my matplotlib version is not works. probably i need to change torch version

**Comment by luisenp** [comment]
Ah sorry, I meant I pushed an additional fix to avoid passing tensors to the plotting code. The latest commit should work with your matplotlib/torch version.

**Comment by app1ep1e** [comment]
:joy: that's all right and it works for me.
