### ISSUE TITLE
[Bug] MBPO on HalfCheetah-v2 not learning

### ISSUE THREAD

**Issue by labecassis** [facebookresearch/mbrl-lib#97]
Hello ! 
Thank you for this new library.

## Steps to reproduce
 I have tried to run MBPO on HalfCheetah-v2 using   
```python -m mbrl.examples.main algorithm=mbpo overrides=mbpo_halfcheetah   ```
after having installed the library, following the README steps.

## Observed Results
Looking at the results.csv file while training MBPO, the agent doesn't seem to be learning:

> env_step,episode_reward,epoch,rollout_length,step
999.0,-0.8456277073670116,0.0,1.0,1
1999.0,-0.9440948246565134,1.0,1.0,2
2999.0,-0.7490316223516877,2.0,1.0,3
3999.0,-0.7571950947415443,3.0,1.0,4
4999.0,-0.8274641044949901,4.0,1.0,5
5999.0,-3.238894348513289,5.0,1.0,6
6999.0,-6.492029299434498,6.0,1.0,7
7999.0,-17.30643762007886,7.0,1.0,8
8999.0,-31.60495724347696,8.0,1.0,9
9999.0,-46.125412228730156,9.0,1.0,10
10999.0,-71.67442837269994,10.0,1.0,11
11999.0,-58.69499608366046,11.0,1.0,12
12999.0,-69.69717022249019,12.0,1.0,13
13999.0,-86.82171969107995,13.0,1.0,14
14999.0,-121.96192444262107,14.0,1.0,15
15999.0,-145.69370999969092,15.0,1.0,16
16999.0,-168.29146007014336,16.0,1.0,17
17999.0,-181.85075223574438,17.0,1.0,18
18999.0,-158.5637693244303,18.0,1.0,19
19999.0,-158.52343716747603,19.0,1.0,20
20999.0,-167.62715189227546,20.0,1.0,21
21999.0,-143.24211684101195,21.0,1.0,22
22999.0,-162.0094559119758,22.0,1.0,23
23999.0,-132.65619703115092,23.0,1.0,24
24999.0,-139.2981737548027,24.0,1.0,25

And the episode_reward values don't get any better ( I have tested it for about 400 000 environment steps).

However, ```python -m mbrl.examples.main algorithm=pets overrides=pets_halfcheetah   ``` gets much better results, with the following result.csv:

> env_step,episode_reward,step
1000.0,-152.01008098334424,1
2000.0,15.21179995149966,2
3000.0,-49.4050625863483,3
4000.0,16.849760830275926,4
5000.0,-219.33720385147777,5
6000.0,-210.56151771405823,6
7000.0,652.796055680682,7
8000.0,902.5875139452987,8
9000.0,1312.0837729671678,9
10000.0,-279.0000574725552,10
11000.0,1753.5399394982003,11
12000.0,1215.2626283022482,12
13000.0,947.9160259748666,13
14000.0,2514.5715560595763,14
15000.0,2619.5086821951263,15
16000.0,3259.5381123355673,16
17000.0,3626.519190884455,17
18000.0,4070.194763445176,18
19000.0,4121.591162199583,19
20000.0,4602.759264114635,20
21000.0,4568.923964106727,21
22000.0,4919.350936975073,22
23000.0,4902.718673117782,23
24000.0,5196.1713305116145,24
25000.0,5124.92839588049,25
26000.0,5283.068158021224,26
27000.0,5191.014333635436,27
28000.0,5345.012072796462,28
29000.0,5019.163125754766,29

## Expected Results

  * I expected the MBPO agent to improve its episode_reward performance, as env_step increases.

Thank you !

**Comment by luisenp** [comment]
Hi @labecassis, thanks for reporting! I'll take a look at this. Have you checked with other seed for the RNG? In my experience performance on HalfCheetah can vary a lot between seeds, and occasionally fail to converge. I'll launch a few on my own to double check, just in case some recent changes broke it completely.

**Comment by luisenp** [comment]
Turns out I pushed the wrong hyperparameter values for HalfCheetah and Ant to the repo. Can you check with the latest version in master branch? Here are results from a partial run with these values over 10 seeds using that config:

![image](https://user-images.githubusercontent.com/4759586/122323006-62364d00-cef4-11eb-8f9a-d634ca0ee126.png)

**Comment by labecassis** [comment]
Hi !
Thanks a lot for investigating that issue. It looks like MBPO is learning now, using the latest version in master branch !

Could you tell me how long it takes for you to run 50 000 or 100 000 timesteps on HalfCheetah-v2 with MBPO?
I would like to compare to what I currently get on my machine: 13 000 environment steps in 2 hours on a gpu and 12 cpu cores.

**Comment by luisenp** [comment]
Great! It took around 4-5 hours of runtime to produce the plot above.

**Comment by luisenp** [comment]
Closed after [this](https://github.com/facebookresearch/mbrl-lib/commit/1bfa0a81ac8e39acd729974addf39f6f95fcd8f0) commit.
